// exercises.js

// We represent the data as Objects now, not Strings.
// This ensures consistency with your main database.

export const EXERCISE_DATABASE = [
  // --- CHEST ---
  { name: 'Barbell Bench Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Incline Barbell Bench Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Decline Barbell Bench Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Dumbbell Bench Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Incline Dumbbell Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Decline Dumbbell Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Chest Dip', muscle: 'Chest', type: 'Compound' },
  { name: 'Push Up', muscle: 'Chest', type: 'Bodyweight' },
  { name: 'Weighted Push Up', muscle: 'Chest', type: 'Compound' },
  { name: 'Diamond Push Up', muscle: 'Chest', type: 'Compound' },
  { name: 'Cable Crossover', muscle: 'Chest', type: 'Isolation' },
  { name: 'Cable Fly (High to Low)', muscle: 'Chest', type: 'Isolation' },
  { name: 'Cable Fly (Low to High)', muscle: 'Chest', type: 'Isolation' },
  { name: 'Dumbbell Fly', muscle: 'Chest', type: 'Isolation' },
  { name: 'Incline Dumbbell Fly', muscle: 'Chest', type: 'Isolation' },
  { name: 'Pec Deck Machine', muscle: 'Chest', type: 'Isolation' },
  { name: 'Machine Chest Press', muscle: 'Chest', type: 'Machine' },
  { name: 'Smith Machine Bench Press', muscle: 'Chest', type: 'Machine' },
  { name: 'Smith Machine Incline Press', muscle: 'Chest', type: 'Machine' },
  { name: 'Landmine Press', muscle: 'Chest', type: 'Compound' },
  { name: 'Svend Press', muscle: 'Chest', type: 'Isolation' },
  { name: 'Floor Press', muscle: 'Chest', type: 'Compound' },

  // --- BACK ---
  { name: 'Deadlift', muscle: 'Back', type: 'Compound' },
  { name: 'Pull Up', muscle: 'Back', type: 'Bodyweight' },
  { name: 'Chin Up', muscle: 'Back', type: 'Bodyweight' },
  { name: 'Weighted Pull Up', muscle: 'Back', type: 'Compound' },
  { name: 'Lat Pulldown (Wide Grip)', muscle: 'Back', type: 'Machine' },
  { name: 'Lat Pulldown (Close Grip)', muscle: 'Back', type: 'Machine' },
  { name: 'Lat Pulldown (Reverse Grip)', muscle: 'Back', type: 'Machine' },
  { name: 'Bent Over Barbell Row', muscle: 'Back', type: 'Compound' },
  { name: 'Pendlay Row', muscle: 'Back', type: 'Compound' },
  { name: 'Yates Row', muscle: 'Back', type: 'Compound' },
  { name: 'T-Bar Row', muscle: 'Back', type: 'Compound' },
  { name: 'Seated Cable Row', muscle: 'Back', type: 'Machine' },
  { name: 'One Arm Dumbbell Row', muscle: 'Back', type: 'Compound' },
  { name: 'Chest Supported Row', muscle: 'Back', type: 'Machine' },
  { name: 'Meadows Row', muscle: 'Back', type: 'Compound' },
  { name: 'Straight Arm Pulldown', muscle: 'Back', type: 'Isolation' },
  { name: 'Dumbbell Pullover', muscle: 'Back', type: 'Isolation' },
  { name: 'Machine Row', muscle: 'Back', type: 'Machine' },
  { name: 'Assisted Pull Up Machine', muscle: 'Back', type: 'Machine' },
  { name: 'Back Extension', muscle: 'Back', type: 'Isolation' },
  { name: 'Hyperextension', muscle: 'Back', type: 'Bodyweight' },
  { name: 'Rack Pull', muscle: 'Back', type: 'Compound' },
  { name: 'Good Morning', muscle: 'Back', type: 'Compound' },
  { name: 'Barbell Shrug', muscle: 'Back', type: 'Isolation' },
  { name: 'Dumbbell Shrug', muscle: 'Back', type: 'Isolation' },

  // --- LEGS ---
  { name: 'Barbell Back Squat', muscle: 'Legs', type: 'Compound' },
  { name: 'Barbell Front Squat', muscle: 'Legs', type: 'Compound' },
  { name: 'Goblet Squat', muscle: 'Legs', type: 'Compound' },
  { name: 'Box Squat', muscle: 'Legs', type: 'Compound' },
  { name: 'Leg Press', muscle: 'Legs', type: 'Machine' },
  { name: 'Hack Squat', muscle: 'Legs', type: 'Machine' },
  { name: 'Romanian Deadlift (RDL)', muscle: 'Legs', type: 'Compound' },
  { name: 'Stiff Leg Deadlift', muscle: 'Legs', type: 'Compound' },
  { name: 'Dumbbell RDL', muscle: 'Legs', type: 'Compound' },
  { name: 'Walking Lunge', muscle: 'Legs', type: 'Compound' },
  { name: 'Reverse Lunge', muscle: 'Legs', type: 'Compound' },
  { name: 'Bulgarian Split Squat', muscle: 'Legs', type: 'Compound' },
  { name: 'Leg Extension', muscle: 'Legs', type: 'Isolation' },
  { name: 'Lying Leg Curl', muscle: 'Legs', type: 'Isolation' },
  { name: 'Seated Leg Curl', muscle: 'Legs', type: 'Isolation' },
  { name: 'Nordic Hamstring Curl', muscle: 'Legs', type: 'Bodyweight' },
  { name: 'Barbell Hip Thrust', muscle: 'Legs', type: 'Compound' },
  { name: 'Glute Bridge', muscle: 'Legs', type: 'Bodyweight' },
  { name: 'Cable Pull Through', muscle: 'Legs', type: 'Isolation' },
  { name: 'Step Up', muscle: 'Legs', type: 'Compound' },
  { name: 'Sissy Squat', muscle: 'Legs', type: 'Bodyweight' },
  { name: 'Standing Calf Raise', muscle: 'Legs', type: 'Isolation' },
  { name: 'Seated Calf Raise', muscle: 'Legs', type: 'Isolation' },
  { name: 'Donkey Calf Raise', muscle: 'Legs', type: 'Isolation' },
  { name: 'Leg Press Calf Raise', muscle: 'Legs', type: 'Isolation' },
  { name: 'Smith Machine Squat', muscle: 'Legs', type: 'Machine' },
  { name: 'Sumo Deadlift', muscle: 'Legs', type: 'Compound' },

  // --- SHOULDERS ---
  { name: 'Overhead Press (OHP)', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Seated Barbell Press', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Arnold Press', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Dumbbell Lateral Raise', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Cable Lateral Raise', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Machine Lateral Raise', muscle: 'Shoulders', type: 'Machine' },
  { name: 'Dumbbell Front Raise', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Plate Front Raise', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Rear Delt Dumbbell Fly', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Rear Delt Machine Fly', muscle: 'Shoulders', type: 'Machine' },
  { name: 'Face Pull', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Upright Row', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Egyptian Lateral Raise', muscle: 'Shoulders', type: 'Isolation' },
  { name: 'Push Press', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Handstand Push Up', muscle: 'Shoulders', type: 'Bodyweight' },
  { name: 'Landmine Shoulder Press', muscle: 'Shoulders', type: 'Compound' },
  { name: 'Behind The Neck Press', muscle: 'Shoulders', type: 'Compound' },

  // --- BICEPS ---
  { name: 'Barbell Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'EZ Bar Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Hammer Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Incline Dumbbell Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Preacher Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Concentration Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Cable Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Bayesian Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Spider Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Reverse Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Zottman Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Chin Up (Bicep Focus)', muscle: 'Biceps', type: 'Compound' },
  { name: 'Waiters Curl', muscle: 'Biceps', type: 'Isolation' },
  { name: 'Machine Bicep Curl', muscle: 'Biceps', type: 'Machine' },

  // --- TRICEPS ---
  { name: 'Tricep Rope Pushdown', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Tricep Bar Pushdown', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Skullcrusher', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Overhead Tricep Extension (DB)', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Overhead Cable Extension', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Close Grip Bench Press', muscle: 'Triceps', type: 'Compound' },
  { name: 'Dips (Tricep Focus)', muscle: 'Triceps', type: 'Compound' },
  { name: 'Bench Dip', muscle: 'Triceps', type: 'Bodyweight' },
  { name: 'Kickback', muscle: 'Triceps', type: 'Isolation' },
  { name: 'JM Press', muscle: 'Triceps', type: 'Compound' },
  { name: 'Single Arm Cable Extension', muscle: 'Triceps', type: 'Isolation' },
  { name: 'Machine Tricep Dip', muscle: 'Triceps', type: 'Machine' },

  // --- CORE ---
  { name: 'Plank', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Side Plank', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Hanging Leg Raise', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Captain\'s Chair Leg Raise', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Cable Crunch', muscle: 'Core', type: 'Machine' },
  { name: 'Russian Twist', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Ab Wheel Rollout', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Mountain Climber', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Bicycle Crunch', muscle: 'Core', type: 'Bodyweight' },
  { name: 'V-Up', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Dragon Flag', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Woodchopper', muscle: 'Core', type: 'Machine' },
  { name: 'Pallof Press', muscle: 'Core', type: 'Isolation' },
  { name: 'Decline Sit Up', muscle: 'Core', type: 'Bodyweight' },
  { name: 'L-Sit', muscle: 'Core', type: 'Bodyweight' },
  { name: 'Vacuum', muscle: 'Core', type: 'Bodyweight' },

  // --- CARDIO / OTHER ---
  { name: 'Treadmill Run', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Cycling', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Rowing Machine', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Elliptical', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Stairmaster', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Jump Rope', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Burpees', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Battle Ropes', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Kettlebell Swing', muscle: 'Legs', type: 'Compound' },
  { name: 'Farmers Walk', muscle: 'Core', type: 'Compound' }
];